Fix 'Show Highlights' in TSPlayground
nvim-treesitter/playground pull request #59
Opened 2021-11-11 22:24 UTC by stephenprater

The extmarks used to highlight syntax with tree-sitter are "ephemeral" and so can't be fetched with `nvim_buf_get_extmarks` - Instead, we need to execute the query against the document and get the highlighted node ranges (exactly like is done for TSHighlightCapturesUnderCursor)

This restores the functionality of showing the highlight groups for a given treesitter node by pressing "i" (or whatever) in the playground - a super handy function.

NB:  If I run this on the `printer.lua` file it get "off" by about the 10th line

![Screen Shot 2021-11-11 at 2 20 49 PM](https://user-images.githubusercontent.com/149870/141377435-49d3ffc0-0a81-4f26-9547-1cbe74a22110.png)
![Screen Shot 2021-11-11 at 2 22 22 PM](https://user-images.githubusercontent.com/149870/141377481-a54798e2-c9eb-4daa-9173-c1ae2279e41a.png)

Obviously, the `=` there is properly highlighted as an operator, so I'm not really sure what's going on there - `TSHighlightCapturesUnderCursor` show the correct group.

2021-11-11 22:24 UTC, stephenprater commented
Fixes #32

2021-11-20 20:46 UTC, theHamsta requested changes
@stephenprater Really nice addition. I wish I had reviewed this PR earlier (had a lot of stress at work last week). I essentially needed the same function you wrote today for another PR https://github.com/nvim-treesitter/nvim-treesitter/pull/2031. Would you mind to extend the `util` function you wrote by a parameter that would return also the captures and intermediate mappings the `:TSHighlightsUnderCursor` has the same functionality as before and also other plugins can use this function that are also interested in the captures?

You could return a table with all the highlight info under cursors (captures, inter-mediate highlights, final highlights, priority)

2022-02-16 15:41 UTC, clason commented
bump. @stephenprater would you be interested in rebasing and finishing this PR?

2022-03-11 10:29 UTC, clason commented
@stsewd could you help resolve the conflict (your recent fix for the intermediate captures needs to be ported to this PR)? 

If it restores the highlight groups and passes tests after this, I'd suggest just merging this PR as is and tackle the refactor in a separate PR (possibly to nvim-treesitter, as this sounds like a useful utility function to have there).

2022-03-29 07:32 UTC, closed without merging

2022-03-29 07:32 UTC, clason commented
superseded by #71