feat!: update to Neovim 0.7 APIs
nvim-treesitter/playground pull request #75
Opened 2022-04-16 11:13 UTC by clason

I would appreciate some testing for regressions since I don't use nearly all features of the Playground (in particular, the query editor and linter).

I could not remove all legacy vimscript since the keymappings are created using string munging, and Lua doesn't have a macro system that would allow similar things natively:
https://github.com/nvim-treesitter/playground/blob/13e2d2d63ce7bc5d875e8bdf89cb070bc8cc7a00/lua/nvim-treesitter-playground/internal.lua#L214

(This will also -- and to an even larger extent -- be a problem for nvim-treesitter itself, for which this PR is something of a dry run.)

2022-04-16 11:16 UTC, clason commented
I feel that the autocommands can also be simplified, since callbacks get passed a table that contains context, such as the buffer (corresponding to `<abuf>`).

2022-04-16 11:53 UTC, clason commented
Regarding the mappings, I think that current design needs to be flipped to have a table
```
["key"] = function
```
(where `function` is an actual Lua function, like telescope does it) rather than, as now,
```
function = "key"
```
(where `function` is a string).

Of course, that would need a fundamental rewrite of the module system, but I think it'd be worth it.

2022-04-18 15:13 UTC, clason commented
Should probably also adapt to the changes in https://github.com/nvim-treesitter/nvim-treesitter/pull/2801

2022-05-01 09:55 UTC, clason commented
@kyazdani42 Would appreciate a look at this PR as well -- I haven't seen any regressions in my testing, but I've never used the query linter.

2022-05-01 12:33 UTC, theHamsta requested changes
Query linter seems to work fine. Playground it self does not work at all and also errors on all other non-playground buffers with
```
Error detected while processing BufLeave Autocommands for "<buffer=6>":                                                                                                                                                                                                           
Error executing lua callback: ...t/playground/lua/nvim-treesitter-playground/internal.lua:765: attempt to call field '_clear_playground_highlights' (a nil value)
stack traceback:
        ...t/playground/lua/nvim-treesitter-playground/internal.lua:765: in function <...t/playground/lua/nvim-treesitter-playground/internal.lua:764>
```

2022-05-01 12:36 UTC, clason commented
Works for me. Can you share how you set up playground?

2022-05-01 12:37 UTC, clason commented
If you use impatient.nvim, make sure you clear the cache after checking out the PR.

2022-05-01 12:53 UTC, clason commented
Ah, forgot to push a fix. Can you try again?

2022-05-01 13:37 UTC, theHamsta approved these changes

2022-05-01 13:46 UTC, merged